In [1]:
# Cell 1: Import Libraries
import torch
import numpy as np

# Explanation: torch is PyTorch's main library. numpy is for comparison.

In [8]:
# Cell 2: Creating Tensors
# Tensors are PyTorch's arrays. They can be 1D, 2D, etc.
tensor_1d = torch.tensor([1, 2, 3, 4])  # 1D tensor
tensor_2d = torch.tensor([[1, 2], [3, 4]])  # 2D tensor (like a matrix)
print("1D Tensor: \n\t", tensor_1d)
print("2D Tensor: \n", tensor_2d)
print("Shape/Dimensions of 2D Tensor:\n\t", tensor_2d.shape)  # Shape shows dimensions

# Explanation: Tensors hold numbers. Shape tells us size (e.g., 2x2 for 2D).

1D Tensor: 
	 tensor([1, 2, 3, 4])
2D Tensor: 
 tensor([[1, 2],
        [3, 4]])
Shape/Dimensions of 2D Tensor:
	 torch.Size([2, 2])


In [15]:
# Cell 3: Basic Operations
# Add, multiply, etc., just like NumPy.
added = tensor_1d + 10  # Add 10 to each element
multiplied = tensor_1d * 2  # Multiply by 2
print("Original:\n", tensor_1d)
print("Original with 10 added:\n", added)
print("Original multiplied by 2:\n", multiplied)

# Reshaping: Change dimensions without changing data.
reshaped = tensor_1d.view(2, 2)  # Turn 4 elements into 2x2
print("Orignal reshaped to 2x2:\n", reshaped)

# Explanation: Operations are element-wise. Reshaping is useful for images (e.g., flatten 28x28 to 784).

Original:
 tensor([1, 2, 3, 4])
Original with 10 added:
 tensor([11, 12, 13, 14])
Original multiplied by 2:
 tensor([2, 4, 6, 8])
Orignal reshaped to 2x2:
 tensor([[1, 2],
        [3, 4]])
